---
language: rust
sudo: false

cache: cargo

matrix:
  include:
  - rust: stable
    before_deploy: cargo doc --no-deps

script:
  - cargo test

deploy:
  provider:  pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  target_branch: gh-pages
  local_dir: target/doc
  on:
    branch: master
    repo: tower-rs/tower-http
    rust: stable

env:
  global:
    - secure: qX5VG/J4gSeDcZqVCpGLrU6EzbchqPC6AkewCNZCWwr2JveHHrZkQV3JV/52QPKB5bl2T5vqXYtNugPcogPRZfPr+BHFOz0gHy5IBc3RXeJpgU9L2oBYqOZllwO0D9IwZ3sFqN/+uRoy9Cjm+H12+lzEOq0B9M7hZ1jUuZmmBUDWzrW0m+fYeuhWIKfGXG7sF5x2OUK56VkOXWe8d6EFJ1+h5EZVxJ4DyWRg07JkOGmQu/MiCLqFexepCwTXWhp1IPrNXnE6/oUtC6alZ4RcolpUf/Cb+/npVRgz3rTysxBLmuqW8f4XdrukiU9p2RP8bilPYTlavB27pbC2s0rI2Z9yyTnWVK6LAbZZIabYyPQNdRGmhqkk98uEo18FXyCM1U9kkB2qdKVYoONXa5Kp/Hghl0myFeQyWikVGCkNuOiJyzKrI8zDLyh6C3buzkBIEk+bpwpQYrzAaSzeiY7wwvGdoQMGt+VtJEC06fxwsKBiI71dpwT5tV5ObSagwQZzExvBafaOYBRy9QwtThKfpiiwJixXFPs3TofrV3uMsMxHKJDOOrZswehnOeAhN3hdiD6iZaQry/4AAWMAVjS34ydY2Bc1wqW2OfsuRpPWJA3RgsZ97cAo1UG1TUuOb12HrpI4IA1bCHoaw3yZoZH7iscSTzKpulNe/pI1KTaJanY=

notifications:
  email:
    on_success: never
